call plug#begin('~/.config/nvim/autoload/plugged')
  Plug 'scrooloose/nerdtree'
  Plug 'sheerun/vim-polyglot'
  Plug 'jiangmiao/auto-pairs'
  Plug 'Valloric/YouCompleteMe'
  Plug 'vim-scripts/indentpython.vim'
  Plug 'vim-syntastic/syntastic'
  Plug 'nvie/vim-flake8'
  Plug 'tmhedberg/SimpylFold'
call plug#end()
